# Generated by Django 3.2.25 on 2024-06-10 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceinfo',
            name='info_memo',
            field=models.TextField(default=datetime.datetime(2024, 6, 11, 4, 59, 50, 780743)),
        ),
    ]
