# Generated by Django 3.2.25 on 2024-06-11 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_resourceinfo_info_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceinfo',
            name='info_memo',
            field=models.TextField(default=datetime.datetime(2024, 6, 11, 14, 46, 39, 489784)),
        ),
    ]
